// flow-typed signature: ab65eced8b3a6b4d6118cd6b49e481b5
// flow-typed version: <<STUB>>/ava_v2.2.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ava'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ava' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ava/cli' {
  declare module.exports: any;
}

declare module 'ava/eslint-plugin-helper' {
  declare module.exports: any;
}

declare module 'ava/lib/api' {
  declare module.exports: any;
}

declare module 'ava/lib/assert' {
  declare module.exports: any;
}

declare module 'ava/lib/babel-pipeline' {
  declare module.exports: any;
}

declare module 'ava/lib/beautify-stack' {
  declare module.exports: any;
}

declare module 'ava/lib/chalk' {
  declare module.exports: any;
}

declare module 'ava/lib/cli' {
  declare module.exports: any;
}

declare module 'ava/lib/code-excerpt' {
  declare module.exports: any;
}

declare module 'ava/lib/concordance-options' {
  declare module.exports: any;
}

declare module 'ava/lib/context-ref' {
  declare module.exports: any;
}

declare module 'ava/lib/create-chain' {
  declare module.exports: any;
}

declare module 'ava/lib/enhance-assert' {
  declare module.exports: any;
}

declare module 'ava/lib/environment-variables' {
  declare module.exports: any;
}

declare module 'ava/lib/extensions' {
  declare module.exports: any;
}

declare module 'ava/lib/fork' {
  declare module.exports: any;
}

declare module 'ava/lib/globs' {
  declare module.exports: any;
}

declare module 'ava/lib/load-config' {
  declare module.exports: any;
}

declare module 'ava/lib/now-and-timers' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/colors' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/format-serialized-error' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/improper-usage-messages' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/mini' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/prefix-title' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/tap' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/verbose' {
  declare module.exports: any;
}

declare module 'ava/lib/reporters/while-corked' {
  declare module.exports: any;
}

declare module 'ava/lib/run-status' {
  declare module.exports: any;
}

declare module 'ava/lib/runner' {
  declare module.exports: any;
}

declare module 'ava/lib/serialize-error' {
  declare module.exports: any;
}

declare module 'ava/lib/snapshot-manager' {
  declare module.exports: any;
}

declare module 'ava/lib/test' {
  declare module.exports: any;
}

declare module 'ava/lib/watcher' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/consume-argv' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/dependency-tracker' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/ensure-forked' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/fake-tty-has-colors' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/fake-tty' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/ipc' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/load-chalk' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/main' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/options' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/precompiler-hook' {
  declare module.exports: any;
}

declare module 'ava/lib/worker/subprocess' {
  declare module.exports: any;
}

declare module 'ava/profile' {
  declare module.exports: any;
}

declare module 'ava/stage-4' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ava/cli.js' {
  declare module.exports: $Exports<'ava/cli'>;
}
declare module 'ava/eslint-plugin-helper.js' {
  declare module.exports: $Exports<'ava/eslint-plugin-helper'>;
}
declare module 'ava/index' {
  declare module.exports: $Exports<'ava'>;
}
declare module 'ava/index.js' {
  declare module.exports: $Exports<'ava'>;
}
declare module 'ava/lib/api.js' {
  declare module.exports: $Exports<'ava/lib/api'>;
}
declare module 'ava/lib/assert.js' {
  declare module.exports: $Exports<'ava/lib/assert'>;
}
declare module 'ava/lib/babel-pipeline.js' {
  declare module.exports: $Exports<'ava/lib/babel-pipeline'>;
}
declare module 'ava/lib/beautify-stack.js' {
  declare module.exports: $Exports<'ava/lib/beautify-stack'>;
}
declare module 'ava/lib/chalk.js' {
  declare module.exports: $Exports<'ava/lib/chalk'>;
}
declare module 'ava/lib/cli.js' {
  declare module.exports: $Exports<'ava/lib/cli'>;
}
declare module 'ava/lib/code-excerpt.js' {
  declare module.exports: $Exports<'ava/lib/code-excerpt'>;
}
declare module 'ava/lib/concordance-options.js' {
  declare module.exports: $Exports<'ava/lib/concordance-options'>;
}
declare module 'ava/lib/context-ref.js' {
  declare module.exports: $Exports<'ava/lib/context-ref'>;
}
declare module 'ava/lib/create-chain.js' {
  declare module.exports: $Exports<'ava/lib/create-chain'>;
}
declare module 'ava/lib/enhance-assert.js' {
  declare module.exports: $Exports<'ava/lib/enhance-assert'>;
}
declare module 'ava/lib/environment-variables.js' {
  declare module.exports: $Exports<'ava/lib/environment-variables'>;
}
declare module 'ava/lib/extensions.js' {
  declare module.exports: $Exports<'ava/lib/extensions'>;
}
declare module 'ava/lib/fork.js' {
  declare module.exports: $Exports<'ava/lib/fork'>;
}
declare module 'ava/lib/globs.js' {
  declare module.exports: $Exports<'ava/lib/globs'>;
}
declare module 'ava/lib/load-config.js' {
  declare module.exports: $Exports<'ava/lib/load-config'>;
}
declare module 'ava/lib/now-and-timers.js' {
  declare module.exports: $Exports<'ava/lib/now-and-timers'>;
}
declare module 'ava/lib/reporters/colors.js' {
  declare module.exports: $Exports<'ava/lib/reporters/colors'>;
}
declare module 'ava/lib/reporters/format-serialized-error.js' {
  declare module.exports: $Exports<'ava/lib/reporters/format-serialized-error'>;
}
declare module 'ava/lib/reporters/improper-usage-messages.js' {
  declare module.exports: $Exports<'ava/lib/reporters/improper-usage-messages'>;
}
declare module 'ava/lib/reporters/mini.js' {
  declare module.exports: $Exports<'ava/lib/reporters/mini'>;
}
declare module 'ava/lib/reporters/prefix-title.js' {
  declare module.exports: $Exports<'ava/lib/reporters/prefix-title'>;
}
declare module 'ava/lib/reporters/tap.js' {
  declare module.exports: $Exports<'ava/lib/reporters/tap'>;
}
declare module 'ava/lib/reporters/verbose.js' {
  declare module.exports: $Exports<'ava/lib/reporters/verbose'>;
}
declare module 'ava/lib/reporters/while-corked.js' {
  declare module.exports: $Exports<'ava/lib/reporters/while-corked'>;
}
declare module 'ava/lib/run-status.js' {
  declare module.exports: $Exports<'ava/lib/run-status'>;
}
declare module 'ava/lib/runner.js' {
  declare module.exports: $Exports<'ava/lib/runner'>;
}
declare module 'ava/lib/serialize-error.js' {
  declare module.exports: $Exports<'ava/lib/serialize-error'>;
}
declare module 'ava/lib/snapshot-manager.js' {
  declare module.exports: $Exports<'ava/lib/snapshot-manager'>;
}
declare module 'ava/lib/test.js' {
  declare module.exports: $Exports<'ava/lib/test'>;
}
declare module 'ava/lib/watcher.js' {
  declare module.exports: $Exports<'ava/lib/watcher'>;
}
declare module 'ava/lib/worker/consume-argv.js' {
  declare module.exports: $Exports<'ava/lib/worker/consume-argv'>;
}
declare module 'ava/lib/worker/dependency-tracker.js' {
  declare module.exports: $Exports<'ava/lib/worker/dependency-tracker'>;
}
declare module 'ava/lib/worker/ensure-forked.js' {
  declare module.exports: $Exports<'ava/lib/worker/ensure-forked'>;
}
declare module 'ava/lib/worker/fake-tty-has-colors.js' {
  declare module.exports: $Exports<'ava/lib/worker/fake-tty-has-colors'>;
}
declare module 'ava/lib/worker/fake-tty.js' {
  declare module.exports: $Exports<'ava/lib/worker/fake-tty'>;
}
declare module 'ava/lib/worker/ipc.js' {
  declare module.exports: $Exports<'ava/lib/worker/ipc'>;
}
declare module 'ava/lib/worker/load-chalk.js' {
  declare module.exports: $Exports<'ava/lib/worker/load-chalk'>;
}
declare module 'ava/lib/worker/main.js' {
  declare module.exports: $Exports<'ava/lib/worker/main'>;
}
declare module 'ava/lib/worker/options.js' {
  declare module.exports: $Exports<'ava/lib/worker/options'>;
}
declare module 'ava/lib/worker/precompiler-hook.js' {
  declare module.exports: $Exports<'ava/lib/worker/precompiler-hook'>;
}
declare module 'ava/lib/worker/subprocess.js' {
  declare module.exports: $Exports<'ava/lib/worker/subprocess'>;
}
declare module 'ava/profile.js' {
  declare module.exports: $Exports<'ava/profile'>;
}
declare module 'ava/stage-4.js' {
  declare module.exports: $Exports<'ava/stage-4'>;
}
