// flow-typed signature: df52d5359cc1b7ca88b1950a80ae35c4
// flow-typed version: <<STUB>>/flow-parser_v^0.86.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-parser/flow_parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-parser/flow_parser.js' {
  declare module.exports: $Exports<'flow-parser/flow_parser'>;
}
